#!/usr/bin/perl

use strict;
use warnings;

use DBI;

use CGI qw(:standard *table); #function based interface to CGI module, start_table and end_table tags
use CGI::Carp qw(fatalsToBrowser); #send errors to browser as well as server error log

use lib '..';
use Mod::DB;
use Mod::Conf;
use Mod::Crypt;

#TODO: set up logger

#Get the list of table names:
my @tables = keys %{ &getSchemas };

#Make the webpage:
print header, start_html('Return To Me');

#Make the banner:
print h1("Return To Me"),
    br(),
    h4('"If you want a professional looking website, go hire a web designer." -- corporate motto'),
    br();

#Make the form:
print start_form,
    "Table: ",
    popup_menu(-name=>'table', -values => [@tables,'All']),
    br,
    "Password: ",
    password_field('key','',10,10),
    br,
    submit,
    end_form;

#Handle form submission:
if (param) {
    my $key = param('key');
    if (param('table') eq 'All') {
	for (@tables) {
	    &displayTable($_,$key);
	}
    } else {	    
	&displayTable(param('table'),$key);
    }
}

print end_html();


sub displayTable {
    my $table_name = shift;
    my $key = shift;

    #Read conf file:
    my $conf_file = "../conf/cli.conf";
    my %conf = %{ &getCipherConf($conf_file,$key) };
    die "Failed to decrypt $conf_file" unless %conf;
    #Check that conf variables are defined:
    my @conf_vars = qw(db_server db_user db_pass);
    for (@conf_vars) {
	unless (defined $conf{$_}) {
	    die "Configuration error: $conf_file does not define $_\n";
	}
    }
    
    #Connect to DB:
    &Mod::DB::connect("mysql:database=" . $conf{db_server},$conf{db_user},$conf{db_pass});
    my @table = @{ &getTable($table_name) };

    #set up the table:
    print start_table({-border=>1});
    print caption("$table_name");
    my $col_names =shift @table;
    print Tr( th( $col_names ) );
    for (@table) {
	my @row_array = @$_;
	print "<tr>";
    my $i = 0;
    for (@row_array) {
	print "<td>";
	
	if ($i == 2 ) { #KLUDGE
	    print '<div style="overflow:auto; height:200px;width:600px;">';
	    $_ = &decrypt($key,$_);
	    print pre($_);
	    print "</div>";
	} else {
	    print;
	}
    	print "</td>";
	$i++;
    }
	print "</tr>";
    }

    print end_table;
    &Mod::DB::disconnect;
}


