#!/usr/bin/perl

use 5.010;

use strict;
use warnings;

use CGI qw(:standard);
print header, start_html('Return To Me');

#Incoming log:
print strong('talariad_incoming.log'), br();
print '<pre>';
system 'cat ../log/talariad_incoming.log';
print '</pre>';
print br();

#Ougoing log:
print strong('talariad_outgoing.log'), br();
print '<pre>';
system 'cat ../log/talariad_outgoing.log';
print '</pre>';
print br();

#Archive log:
print strong('talariad_archive.log'), br();
print '<pre>';
system 'cat ../log/talariad_archive.log';
print '</pre>';
print end_html;

=head1 NAME

viewLog -- CGI script to display talariad logs.

=head1 USAGE

CGI script.

=head1 DESCRIPTION

Uses cat to display all three log files.

=head1 DEPENDENCIES

=over

=item *

CGI

=back
